server {
    listen 80;

    #Set Size Limit For File Uploads (Profile Photos & Post Photos)
    client_max_body_size 500M;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # ✅ React se /api/ calls backend ko jaayengi
    location /api/ {
        proxy_pass http://twine-backend:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #For Authentication Headers (Cookies & Authorization)
        proxy_set_header Cookie $http_cookie;       
        proxy_set_header Authorization $http_authorization; 

        # Increase timeouts for long-running requests (like file uploads)
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        # For WebSocket Support (if needed in future)
        proxy_http_version 1.1;
        proxy_set_header Connection ""; 
    }
}